<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="generator" content="litedown 0.9">
<title>Semántica de referencia</title>
<style type="text/css">
body {
  font-family: sans-serif;
  max-width: 800px;
  margin: auto;
  padding: 1em;
  line-height: 1.5;
  print-color-adjust: exact;
  -webkit-print-color-adjust: exact;
}
body, .abstract, code, .footnotes, footer, #refs, .caption { font-size: .9em; }
li li { font-size: .95em; }
ul:has(li > input[type="checkbox"]) { list-style: none; padding-left: 1em; }
*, :before, :after { box-sizing: border-box; }
a { color: steelblue; }
pre, img { max-width: 100%; }
pre { white-space: pre-wrap; word-break: break-word; }
pre code { display: block; padding: 1em; overflow-x: auto; }
code { font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace; }
:not(pre, th) > code, code[class], div > .caption { background: #f8f8f8; }
pre > code:is(:not([class]), .language-plain, .language-none, .plain), .box, .figure, .table { background: inherit; border: 1px solid #eee; }
pre > code {
  &.message { border-color: #9eeaf9; }
  &.warning { background: #fff3cd; border-color: #fff3cd; }
  &.error { background: #f8d7da; border-color: #f8d7da; }
}
.fenced-chunk { border-left: 1px solid #666; }
.code-fence {
  opacity: .4;
  border: 1px dashed #666;
  border-left: 2px solid;
  &:hover { opacity: inherit; }
}
.box, .figure, .table, table { margin: 1em auto; }
div > .caption { padding: 1px 1em; }
.figure { p:has(img, svg), pre:has(svg) { text-align: center; } }
.flex-col { display: flex; justify-content: space-between; }
table {
  &:only-child:not(.table > *) { margin: auto; }
  th, td { padding: 5px; font-variant-numeric: tabular-nums; }
  thead, tfoot, tr:nth-child(even) { background: whitesmoke; }
  thead th { border-bottom: 1px solid #ddd; }
  &:not(.datatable-table) {
    border-top: 1px solid #666;
    border-bottom: 1px solid #666;
  }
}
blockquote {
  color: #666;
  margin: 0;
  padding: 1px 1em;
  border-left: .5em solid #eee;
}
hr, .footnotes::before { border: 1px dashed #ddd; }
.frontmatter { text-align: center; }
#TOC {
  a { text-decoration: none; }
  ul { list-style: none; padding-left: 1em; }
  & > ul { padding: 0; }
  ul ul { border-left: 1px solid lightsteelblue; }
}
.body h2 { border-bottom: 1px solid #666; }
.body .appendix, .appendix ~ h2 { border-bottom-style: dashed; }
.main-number::after { content: "."; }
span[class^="ref-number-"] { font-weight: bold; }
.ref-number-fig::after, .ref-number-tab::after { content: ":"; }
.cross-ref-chp::before { content: "Chapter "; }
.cross-ref-sec::before { content: "Section "; }
.cross-ref-fig::before, .ref-number-fig::before { content: "Figure "; }
.cross-ref-tab::before, .ref-number-tab::before { content: "Table "; }
.cross-ref-eqn::before, .MathJax_ref:has(mjx-mtext > mjx-c + mjx-c)::before { content: "Equation "; }
.abstract, #refs {
  &::before { display: block; margin: 1em auto; font-weight: bold; }
}
.abstract::before { content: "Abstract"; text-align: center; }
#refs::before { content: "Bibliography"; font-size: 1.5em; }
.ref-paren-open::before { content: "("; }
.ref-paren-close::after { content: ")"; }
.ref-semicolon::after { content: "; "; }
.ref-and::after { content: " and "; }
.ref-et-al::after { content: " et al."; font-style: italic; }
.footnote-ref a {
  &::before { content: "["; }
  &::after { content: "]"; }
}
section.footnotes {
  margin-top: 2em;
  &::before { content: ""; display: block; max-width: 20em; }
}
.fade {
  background: repeating-linear-gradient(135deg, white, white 30px, #ddd 32px, #ddd 32px);
  opacity: 0.6;
}

@media print {
  body { max-width: 100%; }
  tr, img { break-inside: avoid; }
}
@media only screen and (min-width: 992px) {
  body:not(.pagesjs) pre:has(.line-numbers):not(:hover) { white-space: pre; }
}
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@xiee/utils@1.14.10/css/prism-xcode.min.css">
</head>
<body>
<div class="frontmatter">
<div class="title"><h1>Semántica de referencia</h1></div>
<div class="date"><h3><code>{r} Sys.Date()</code></h3></div>
</div>
<div class="body">
<p><code>{r} .write.translation.links(&quot;Las traducciones de este documento están disponibles en: %s&quot;)</code></p>
<p>Esta viñeta describe la semántica por referencia de <em>data.table</em>, que permite <em>añadir/actualizar/eliminar</em> columnas de una <em>data.table</em> por referencia*, así como combinarlas con <code>i</code> y <code>by</code>. Está dirigida a quienes ya están familiarizados con la sintaxis de <em>data.table</em>, su forma general, cómo crear subconjuntos de filas en <code>i</code>, seleccionar y calcular columnas, y realizar agregaciones por grupo. Si no está familiarizado con estos conceptos, lea primero la viñeta <a href="datatable-intro.html"><code>vignette(&quot;datatable-intro&quot;, package=&quot;data.table&quot;)</code></a>.</p>
<hr />
<h2 id="data">Datos</h2>
<p>Utilizaremos los mismos datos de <code>flights</code> que en la viñeta <a href="datatable-intro.html"><code>vignette(&quot;datatable-intro&quot;, package=&quot;data.table&quot;)</code></a>.</p>
<pre><code class="language-r">flights &lt;- fread(&quot;../flights14.csv&quot;)
flights
</code></pre>
<pre><code>##          year month   day dep_delay arr_delay carrier origin   dest air_time distance  hour
##         &lt;int&gt; &lt;int&gt; &lt;int&gt;     &lt;int&gt;     &lt;int&gt;  &lt;char&gt; &lt;char&gt; &lt;char&gt;    &lt;int&gt;    &lt;int&gt; &lt;int&gt;
##      1:  2014     1     1        14        13      AA    JFK    LAX      359     2475     9
##      2:  2014     1     1        -3        13      AA    JFK    LAX      363     2475    11
##      3:  2014     1     1         2         9      AA    JFK    LAX      351     2475    19
##      4:  2014     1     1        -8       -26      AA    LGA    PBI      157     1035     7
##      5:  2014     1     1         2         1      AA    JFK    LAX      350     2475    13
##     ---                                                                                    
## 253312:  2014    10    31         1       -30      UA    LGA    IAH      201     1416    14
## 253313:  2014    10    31        -5       -14      UA    EWR    IAH      189     1400     8
## 253314:  2014    10    31        -8        16      MQ    LGA    RDU       83      431    11
## 253315:  2014    10    31        -4        15      MQ    LGA    DTW       75      502    11
## 253316:  2014    10    31        -5         1      MQ    LGA    SDF      110      659     8
</code></pre>
<pre><code class="language-r">dim(flights)
</code></pre>
<pre><code>## [1] 253316     11
</code></pre>
<h2 id="sec:introducci-n">Introducción</h2>
<p>En esta viñeta, vamos a:</p>
<ol>
<li>
<p>Primero analicemos brevemente la semántica por referencia y observemos las dos formas diferentes en las que se puede utilizar el operador <code>:=</code></p>
</li>
<li>
<p>Luego veamos cómo podemos <em>agregar/actualizar/eliminar</em> columnas <em>por referencia</em> en <code>j</code> usando el operador <code>:=</code> y cómo combinarlo con <code>i</code> y <code>by</code>.</p>
</li>
<li>
<p>y finalmente veremos el uso de <code>:=</code> por sus <em>efectos secundarios</em> y cómo podemos evitar los efectos secundarios usando <code>copy()</code>.</p>
</li>
</ol>
<h2 id="sec:1-sem-ntica-por-referencia">1. Semántica por referencia</h2>
<p>Todas las operaciones que vimos en la viñeta anterior generaron un nuevo conjunto de datos. Veremos cómo <em>añadir</em> nuevas columnas, <em>actualizar</em> o <em>eliminar</em> columnas existentes en los datos originales.</p>
<h3 id="sec:a-antecedentes">a) Antecedentes</h3>
<p>Antes de analizar la <em>semántica por referencia</em>, considere el <em>data.frame</em> que se muestra a continuación:</p>
<pre><code class="language-r">DF = data.frame(ID = c(&quot;b&quot;,&quot;b&quot;,&quot;b&quot;,&quot;a&quot;,&quot;a&quot;,&quot;c&quot;), a = 1:6, b = 7:12, c = 13:18)
DF
</code></pre>
<pre><code>##   ID a  b  c
## 1  b 1  7 13
## 2  b 2  8 14
## 3  b 3  9 15
## 4  a 4 10 16
## 5  a 5 11 17
## 6  c 6 12 18
</code></pre>
<p>Cuando lo hicimos:</p>
<pre><code class="language-r">DF$c &lt;- 18:13               # (1) -- replace entire column
# or
DF$c[DF$ID == &quot;b&quot;] &lt;- 15:13 # (2) -- subassign in column 'c'
</code></pre>
<p>Tanto (1) como (2) resultaban en una copia profunda de todo el data.frame en versiones de <code>R &lt; 3.1</code>. <a href="https://stackoverflow.com/q/23898969/559784">Se copiaba más de una vez</a>. Para mejorar el rendimiento y evitar estas copias redundantes, <em>data.table</em> utilizó el operador <code>:=</code> <a href="https://stackoverflow.com/q/7033106/559784">disponible pero no utilizado en R</a>.</p>
<p>Se implementaron importantes mejoras de rendimiento en <code>R v3.1</code>, lo que permite realizar una copia superficial para (1) y no una copia profunda. Sin embargo, para (2), la columna completa se copia en profundidad, incluso en <code>R v3.1+</code>. Esto significa que cuantas más columnas se subasignan en la misma consulta, más copias profundas realiza R.</p>
<h4 id="sec:copia-superficial-vs-copia-profunda">Copia <em>superficial</em> vs. copia <em>profunda</em></h4>
<p>Una copia superficial es simplemente una copia del vector de punteros de columna (correspondientes a las columnas de un data.frame o una data.table). Los datos reales no se copian físicamente en la memoria.</p>
<p>Una copia <em>profunda</em>, por otro lado, copia todos los datos a otra ubicación en la memoria.</p>
<p>Al crear un subconjunto de una tabla de datos (data.table) mediante <code>i</code> (p. ej., <code>DT[1:10]</code>), se realiza una copia profunda. Sin embargo, si <code>i</code> no se proporciona o es igual a <code>TRUE</code>, se realiza una copia superficial.</p>
<h1></h1>
<p>Con el operador <code>:=</code> de <em>data.table</em>, no se realizan copias en (1) ni (2), independientemente de la versión de R que se utilice. Esto se debe a que el operador <code>:=</code> actualiza las columnas de <em>data.table</em> in situ (por referencia).</p>
<h3 id="sec:b-el-operador">b) El operador <code>:=</code></h3>
<p>Se puede utilizar en <code>j</code> de dos maneras:</p>
<p>(a) La forma <code>LHS := RHS</code></p>
<pre><code class="language-r">DT[, c(&quot;colA&quot;, &quot;colB&quot;, ...) := list(valA, valB, ...)]

# when you have only one column to assign to you
# can drop the quotes and list(), for convenience
DT[, colA := valA]
</code></pre>
<p>(b) La forma funcional</p>
<pre><code class="language-r">DT[, `:=`(colA = valA, # valA is assigned to colA
          colB = valB, # valB is assigned to colB
          ...
)]
</code></pre>
<p>Tenga en cuenta que el código anterior explica cómo usar <code>:=</code>. No son ejemplos prácticos. Comenzaremos a usarlos en la tabla de datos <code>flights</code> a partir de la siguiente sección.</p>
<h1></h1>
<ul>
<li>
<p>En (a), <code>LHS</code> toma un vector de caracteres de nombres de columnas y <code>RHS</code> una <em>lista de valores</em>. <code>RHS</code> solo necesita ser una <code>lista</code>, independientemente de cómo se genere (p. ej., usando <code>lapply()</code>, <code>list()</code>, <code>mget()</code>, <code>mapply()</code>, etc.). Esta forma suele ser fácil de programar y es especialmente útil cuando no se conocen de antemano las columnas a las que se asignarán valores.</p>
</li>
<li>
<p>Por otro lado, (b) es útil si desea anotar algunos comentarios para más tarde.</p>
</li>
<li>
<p>El resultado se devuelve <em>de forma invisible</em>.</p>
</li>
<li>
<p>Dado que <code>:=</code> está disponible en <code>j</code>, podemos combinarlo con las operaciones <code>i</code> y <code>by</code> tal como las operaciones de agregación que vimos en la viñeta anterior.</p>
</li>
</ul>
<h1></h1>
<p>En las dos formas de <code>:=</code> mostradas arriba, observe que no asignamos el resultado a una variable, ya que no es necesario. La entrada <em>data.table</em> se modifica por referencia. Veamos algunos ejemplos para comprender a qué nos referimos.</p>
<p>Para el resto de la viñeta, trabajaremos con la tabla de datos <em>flights</em>.</p>
<h2 id="sec:2-agregar-actualizar-eliminar-columnas-por-referencia">2. Agregar/actualizar/eliminar columnas <em>por referencia</em></h2>
<h3 id="ref-j">a) Agregar columnas por referencia</h3>
<h4 id="sec:c-mo-podemos-agregar-las-columnas-velocidad-y-retraso-total-de-cada-vuelo-a-la-tabla-de-datos-flights">– ¿Cómo podemos agregar las columnas <em>velocidad</em> y <em>retraso total</em> de cada vuelo a la tabla de datos <em>flights</em>?</h4>
<pre><code class="language-r">flights[, `:=`(speed = distance / (air_time/60), # speed in mph (mi/h)
               delay = arr_delay + dep_delay)]   # delay in minutes
head(flights)
</code></pre>
<pre><code>##     year month   day dep_delay arr_delay carrier origin   dest air_time distance  hour    speed
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;     &lt;int&gt;     &lt;int&gt;  &lt;char&gt; &lt;char&gt; &lt;char&gt;    &lt;int&gt;    &lt;int&gt; &lt;int&gt;    &lt;num&gt;
## 1:  2014     1     1        14        13      AA    JFK    LAX      359     2475     9 413.6490
## 2:  2014     1     1        -3        13      AA    JFK    LAX      363     2475    11 409.0909
## 3:  2014     1     1         2         9      AA    JFK    LAX      351     2475    19 423.0769
## 4:  2014     1     1        -8       -26      AA    LGA    PBI      157     1035     7 395.5414
## 5:  2014     1     1         2         1      AA    JFK    LAX      350     2475    13 424.2857
## 6:  2014     1     1         4         0      AA    EWR    LAX      339     2454    18 434.3363
##    delay
##    &lt;int&gt;
## 1:    27
## 2:    10
## 3:    11
## 4:   -34
## 5:     3
## 6:     4
</code></pre>
<pre><code class="language-r">## alternatively, using the 'LHS := RHS' form
# flights[, c(&quot;speed&quot;, &quot;delay&quot;) := list(distance/(air_time/60), arr_delay + dep_delay)]
</code></pre>
<h4 id="sec:tenga-en-cuenta-que">Tenga en cuenta que</h4>
<ul>
<li>
<p>No tuvimos que volver a asignar el resultado a <code>flights</code>.</p>
</li>
<li>
<p>La tabla de datos <code>flights</code> ahora contiene las dos columnas recién añadidas. Esto es lo que queremos decir con <code>añadidas por referencia</code>.</p>
</li>
<li>
<p>Usamos la forma funcional para poder agregar comentarios al margen y explicar el cálculo. También puedes ver la forma <code>LHS := RHS</code> (comentada).</p>
</li>
</ul>
<h3 id="ref-ij">b) Actualizar algunas filas de columnas por referencia - <em>sub-asignar</em> por referencia</h3>
<p>Echemos un vistazo a todas las <code>hours</code> disponibles en la <em>data.table</em> <code>flights</code>:</p>
<pre><code class="language-r"># get all 'hours' in flights
flights[, sort(unique(hour))]
</code></pre>
<pre><code>##  [1]  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
</code></pre>
<p>Observamos que hay un total de <code>25</code> valores únicos en los datos. Parece que hay tanto <em>0</em> como <em>24</em> horas. Reemplacemos <em>24</em> por <em>0</em>.</p>
<h4 id="sec:reemplace-aquellas-filas-donde-hora-24-con-el-valor-0">– Reemplace aquellas filas donde <code>hora == 24</code> con el valor <code>0</code></h4>
<pre><code class="language-r"># subassign by reference
flights[hour == 24L, hour := 0L]
</code></pre>
<ul>
<li>
<p>Podemos usar <code>i</code> junto con <code>:=</code> en <code>j</code> de la misma manera que ya hemos visto en la viñeta <a href="datatable-intro.html"><code>vignette(&quot;datatable-intro&quot;, package=&quot;data.table&quot;)</code></a>.</p>
</li>
<li>
<p>La columna <code>hora</code> se reemplaza con <code>0</code> solo en aquellos <em>índices de fila</em> donde la condición <code>hora == 24L</code> especificada en <code>i</code> se evalúa como <code>VERDADERO</code>.</p>
</li>
<li>
<p><code>:=</code> devuelve el resultado de forma invisible. A veces, puede ser necesario ver el resultado después de la asignación. Podemos lograrlo añadiendo un <code>[]</code> vacío al final de la consulta, como se muestra a continuación:</p>
<pre><code class="language-r">flights[hour == 24L, hour := 0L][]
</code></pre>
<pre><code>## Índice: &lt;hour&gt;
##          year month   day dep_delay arr_delay carrier origin   dest air_time distance  hour
##         &lt;int&gt; &lt;int&gt; &lt;int&gt;     &lt;int&gt;     &lt;int&gt;  &lt;char&gt; &lt;char&gt; &lt;char&gt;    &lt;int&gt;    &lt;int&gt; &lt;int&gt;
##      1:  2014     1     1        14        13      AA    JFK    LAX      359     2475     9
##      2:  2014     1     1        -3        13      AA    JFK    LAX      363     2475    11
##      3:  2014     1     1         2         9      AA    JFK    LAX      351     2475    19
##      4:  2014     1     1        -8       -26      AA    LGA    PBI      157     1035     7
##      5:  2014     1     1         2         1      AA    JFK    LAX      350     2475    13
##     ---                                                                                    
## 253312:  2014    10    31         1       -30      UA    LGA    IAH      201     1416    14
## 253313:  2014    10    31        -5       -14      UA    EWR    IAH      189     1400     8
## 253314:  2014    10    31        -8        16      MQ    LGA    RDU       83      431    11
## 253315:  2014    10    31        -4        15      MQ    LGA    DTW       75      502    11
## 253316:  2014    10    31        -5         1      MQ    LGA    SDF      110      659     8
##            speed delay
##            &lt;num&gt; &lt;int&gt;
##      1: 413.6490    27
##      2: 409.0909    10
##      3: 423.0769    11
##      4: 395.5414   -34
##      5: 424.2857     3
##     ---               
## 253312: 422.6866   -29
## 253313: 444.4444   -19
## 253314: 311.5663     8
## 253315: 401.6000    11
## 253316: 359.4545    -4
</code></pre>
</li>
</ul>
<h1></h1>
<p>Veamos todas las <code>hours</code> para verificar.</p>
<pre><code class="language-r"># check again for '24'
flights[, sort(unique(hour))]
</code></pre>
<pre><code>##  [1]  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
</code></pre>
<h4 id="update-by-reference-question">Ejercicio:</h4>
<p>¿Cuál es la diferencia entre <code>flights[hour == 24L, hour := 0L]</code> y <code>flights[hour == 24L][, hour := 0L]</code>? Consejo: Este último requiere una asignación (<code>&lt;-</code>) si desea usar el resultado posteriormente.</p>
<p>Si no puede resolverlo, eche un vistazo a la sección “Nota” de “?”:=”`.</p>
<h3 id="sec:c-eliminar-columna-por-referencia">c) Eliminar columna por referencia</h3>
<h4 id="sec:eliminar-la-columna-delay">– Eliminar la columna <code>delay</code></h4>
<pre><code class="language-r">flights[, c(&quot;delay&quot;) := NULL]
head(flights)
</code></pre>
<pre><code>##     year month   day dep_delay arr_delay carrier origin   dest air_time distance  hour    speed
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;     &lt;int&gt;     &lt;int&gt;  &lt;char&gt; &lt;char&gt; &lt;char&gt;    &lt;int&gt;    &lt;int&gt; &lt;int&gt;    &lt;num&gt;
## 1:  2014     1     1        14        13      AA    JFK    LAX      359     2475     9 413.6490
## 2:  2014     1     1        -3        13      AA    JFK    LAX      363     2475    11 409.0909
## 3:  2014     1     1         2         9      AA    JFK    LAX      351     2475    19 423.0769
## 4:  2014     1     1        -8       -26      AA    LGA    PBI      157     1035     7 395.5414
## 5:  2014     1     1         2         1      AA    JFK    LAX      350     2475    13 424.2857
## 6:  2014     1     1         4         0      AA    EWR    LAX      339     2454    18 434.3363
</code></pre>
<pre><code class="language-r">## or using the functional form
# flights[, `:=`(delay = NULL)]
</code></pre>
<h4 id="sec:eliminar-conveniencia">{#eliminar-conveniencia}</h4>
<ul>
<li>
<p>Asignar <code>NULL</code> a una columna <em>elimina</em> esa columna. Y esto sucede <em>instantáneamente</em>.</p>
</li>
<li>
<p>También podemos pasar números de columnas en lugar de nombres en el <code>LHS</code>, aunque es una buena práctica de programación usar nombres de columnas.</p>
</li>
<li>
<p>Cuando solo hay una columna para eliminar, podemos omitir <code>c()</code> y las comillas dobles y usar solo el nombre de la columna <em>sin comillas</em>, para mayor comodidad. Es decir:</p>
<pre><code class="language-r">flights[, delay := NULL]
</code></pre>
<p>is equivalent to the code above.</p>
</li>
</ul>
<h3 id="ref-j-by">d) <code>:=</code> junto con la agrupación usando <code>by</code></h3>
<p>Ya vimos el uso de <code>i</code> junto con <code>:=</code> en la <a href="#ref-ij">Sección 2b</a>. Veamos ahora cómo podemos usar <code>:=</code> junto con <code>by</code>.</p>
<h4 id="sec:c-mo-podemos-agregar-una-nueva-columna-que-contenga-para-cada-par-orig-dest-la-velocidad-m-xima">– ¿Cómo podemos agregar una nueva columna que contenga para cada par ‘orig,dest’ la velocidad máxima?</h4>
<pre><code class="language-r">flights[, max_speed := max(speed), by = .(origin, dest)]
head(flights)
</code></pre>
<pre><code>##     year month   day dep_delay arr_delay carrier origin   dest air_time distance  hour    speed
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;     &lt;int&gt;     &lt;int&gt;  &lt;char&gt; &lt;char&gt; &lt;char&gt;    &lt;int&gt;    &lt;int&gt; &lt;int&gt;    &lt;num&gt;
## 1:  2014     1     1        14        13      AA    JFK    LAX      359     2475     9 413.6490
## 2:  2014     1     1        -3        13      AA    JFK    LAX      363     2475    11 409.0909
## 3:  2014     1     1         2         9      AA    JFK    LAX      351     2475    19 423.0769
## 4:  2014     1     1        -8       -26      AA    LGA    PBI      157     1035     7 395.5414
## 5:  2014     1     1         2         1      AA    JFK    LAX      350     2475    13 424.2857
## 6:  2014     1     1         4         0      AA    EWR    LAX      339     2454    18 434.3363
##    max_speed
##        &lt;num&gt;
## 1:  526.5957
## 2:  526.5957
## 3:  526.5957
## 4:  517.5000
## 5:  526.5957
## 6:  518.4507
</code></pre>
<ul>
<li>
<p>Agregamos una nueva columna <code>max_speed</code> usando el operador <code>:=</code> por referencia.</p>
</li>
<li>
<p>Proporcionamos las columnas para agrupar de la misma manera que se muestra en la viñeta <em>Introducción a data.table</em>. Para cada grupo, se calcula <code>max(speed)</code>, que devuelve un único valor. Este valor se recicla para ajustarse a la longitud del grupo. Nuevamente, no se realizan copias. La tabla <code>flights</code> <em>data.table</em> se modifica <em>in situ</em>.</p>
</li>
<li>
<p>También podríamos haber proporcionado <code>by</code> con un <em>vector de caracteres</em> como vimos en la viñeta <a href="datatable-intro.html"><code>vignette(&quot;datatable-intro&quot;, package=&quot;data.table&quot;)</code></a>, por ejemplo, <code>by = c(&quot;origin&quot;, &quot;dest&quot;)</code>.</p>
</li>
</ul>
<h1></h1>
<h3 id="sec:e-varias-columnas-y">e) Varias columnas y <code>:=</code></h3>
<h4 id="sec:c-mo-podemos-agregar-dos-columnas-m-s-calculando-max-de-dep-delay-y-arr-delay-para-cada-mes-usando-sd">– ¿Cómo podemos agregar dos columnas más calculando <code>max()</code> de <code>dep_delay</code> y <code>arr_delay</code> para cada mes, usando <code>.SD</code>?</h4>
<pre><code class="language-r">in_cols  = c(&quot;dep_delay&quot;, &quot;arr_delay&quot;)
out_cols = c(&quot;max_dep_delay&quot;, &quot;max_arr_delay&quot;)
flights[, c(out_cols) := lapply(.SD, max), by = month, .SDcols = in_cols]
head(flights)
</code></pre>
<pre><code>##     year month   day dep_delay arr_delay carrier origin   dest air_time distance  hour    speed
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;     &lt;int&gt;     &lt;int&gt;  &lt;char&gt; &lt;char&gt; &lt;char&gt;    &lt;int&gt;    &lt;int&gt; &lt;int&gt;    &lt;num&gt;
## 1:  2014     1     1        14        13      AA    JFK    LAX      359     2475     9 413.6490
## 2:  2014     1     1        -3        13      AA    JFK    LAX      363     2475    11 409.0909
## 3:  2014     1     1         2         9      AA    JFK    LAX      351     2475    19 423.0769
## 4:  2014     1     1        -8       -26      AA    LGA    PBI      157     1035     7 395.5414
## 5:  2014     1     1         2         1      AA    JFK    LAX      350     2475    13 424.2857
## 6:  2014     1     1         4         0      AA    EWR    LAX      339     2454    18 434.3363
##    max_speed max_dep_delay max_arr_delay
##        &lt;num&gt;         &lt;int&gt;         &lt;int&gt;
## 1:  526.5957           973           996
## 2:  526.5957           973           996
## 3:  526.5957           973           996
## 4:  517.5000           973           996
## 5:  526.5957           973           996
## 6:  518.4507           973           996
</code></pre>
<ul>
<li>
<p>Usamos el formato <code>LHS := RHS</code>. Almacenamos los nombres de las columnas de entrada y las nuevas columnas que se agregarán en variables separadas y las proporcionamos a <code>.SDcols</code> y a <code>LHS</code> (para una mejor legibilidad).</p>
</li>
<li>
<p>Tenga en cuenta que, dado que permitimos la asignación por referencia sin comillas en los nombres de columna cuando solo hay una columna, como se explica en la <a href="#delete-convenience">Sección 2c</a>, no podemos usar <code>out_cols := lapply(.SD, max)</code>. Esto resultaría en agregar una nueva columna llamada <code>out_cols</code>. En su lugar, deberíamos usar <code>c(out_cols)</code> o simplemente <code>(out_cols)</code>. Encapsular el nombre de la variable con <code>(</code> es suficiente para diferenciar entre ambos casos.</p>
</li>
<li>
<p>La forma <code>LHS := RHS</code> permite operar en múltiples columnas. En el lado derecho, para calcular el <code>máximo</code> en las columnas especificadas en <code>.SDcols</code>, utilizamos la función base <code>lapply()</code> junto con <code>.SD</code>, tal como vimos anteriormente en la viñeta <a href="datatable-intro.html"><code>vignette(&quot;datatable-intro&quot;, package=&quot;data.table&quot;)</code></a>. Esta función devuelve una lista de dos elementos, que contiene el valor máximo correspondiente a <code>dep_delay</code> y <code>arr_delay</code> para cada grupo.</p>
</li>
</ul>
<h1></h1>
<p>Antes de pasar a la siguiente sección, limpiemos las columnas recién creadas <code>speed</code>, <code>max_speed</code>, <code>max_dep_delay</code> y <code>max_arr_delay</code>.</p>
<pre><code class="language-r"># RHS gets automatically recycled to length of LHS
flights[, c(&quot;speed&quot;, &quot;max_speed&quot;, &quot;max_dep_delay&quot;, &quot;max_arr_delay&quot;) := NULL]
head(flights)
</code></pre>
<pre><code>##     year month   day dep_delay arr_delay carrier origin   dest air_time distance  hour
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;     &lt;int&gt;     &lt;int&gt;  &lt;char&gt; &lt;char&gt; &lt;char&gt;    &lt;int&gt;    &lt;int&gt; &lt;int&gt;
## 1:  2014     1     1        14        13      AA    JFK    LAX      359     2475     9
## 2:  2014     1     1        -3        13      AA    JFK    LAX      363     2475    11
## 3:  2014     1     1         2         9      AA    JFK    LAX      351     2475    19
## 4:  2014     1     1        -8       -26      AA    LGA    PBI      157     1035     7
## 5:  2014     1     1         2         1      AA    JFK    LAX      350     2475    13
## 6:  2014     1     1         4         0      AA    EWR    LAX      339     2454    18
</code></pre>
<h4 id="sec:c-mo-podemos-actualizar-varias-columnas-existentes-usando-sd">– ¿Cómo podemos actualizar varias columnas existentes usando <code>.SD</code>?</h4>
<pre><code class="language-r">flights[, names(.SD) := lapply(.SD, as.factor), .SDcols = is.character]
</code></pre>
<p>Limpiemos de nuevo y convirtamos nuestras columnas de factores recién creadas en columnas de caracteres. Esta vez, usaremos <code>.SDcols</code>, que acepta una función para decidir qué columnas incluir. En este caso, <code>is.factor()</code> devolverá las columnas que son factores. Para más información sobre el <strong>S</strong>subconjunto de <strong>D</strong>atos, también hay una viñeta de uso de SD (<a href="https://cran.r-project.org/package=data.table/vignettes/datatable-sd-usage.html">https://cran.r-project.org/package=data.table/vignettes/datatable-sd-usage.html</a>).</p>
<p>A veces, también es útil llevar un registro de las columnas que transformamos. De esta manera, incluso después de convertirlas, podremos llamar a las columnas específicas que actualizamos.</p>
<pre><code class="language-r">factor_cols &lt;- sapply(flights, is.factor)
flights[, names(.SD) := lapply(.SD, as.character), .SDcols = factor_cols]
str(flights[, ..factor_cols])
</code></pre>
<pre><code>## Classes 'data.table' and 'data.frame':	253316 obs. of  3 variables:
##  $ carrier: chr  &quot;AA&quot; &quot;AA&quot; &quot;AA&quot; &quot;AA&quot; ...
##  $ origin : chr  &quot;JFK&quot; &quot;JFK&quot; &quot;JFK&quot; &quot;LGA&quot; ...
##  $ dest   : chr  &quot;LAX&quot; &quot;LAX&quot; &quot;LAX&quot; &quot;PBI&quot; ...
##  - attr(*, &quot;.internal.selfref&quot;)=&lt;externalptr&gt;
</code></pre>
<h4 id="sec:bs-callout-bs-callout-info">{.bs-callout .bs-callout-info}</h4>
<ul>
<li>También podríamos haber usado <code>(factor_cols)</code> en el <code>LHS</code> en lugar de <code>names(.SD)</code>.</li>
</ul>
<h2 id="sec:3-y-copy">3. <code>:=</code> y <code>copy()</code></h2>
<p><code>:=</code> modifica el objeto de entrada por referencia. Además de las funciones que ya hemos mencionado, a veces podríamos querer usar la función de actualización por referencia por su efecto secundario. En otras ocasiones, puede que no sea conveniente modificar el objeto original, en cuyo caso podemos usar la función <code>copy()</code>, como veremos en breve.</p>
<h3 id="sec:a-por-su-efecto-secundario">a) <code>:=</code> por su efecto secundario</h3>
<p>Supongamos que queremos crear una función que devuelva la <em>velocidad máxima</em> de cada mes. Pero, al mismo tiempo, también queremos añadir la columna <code>velocidad</code> a <code>flights</code>. Podríamos escribir una función simple como la siguiente:</p>
<pre><code class="language-r">foo &lt;- function(DT) {
  DT[, speed := distance / (air_time/60)]
  DT[, .(max_speed = max(speed)), by = month]
}
ans = foo(flights)
head(flights)
</code></pre>
<pre><code>##     year month   day dep_delay arr_delay carrier origin   dest air_time distance  hour    speed
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;     &lt;int&gt;     &lt;int&gt;  &lt;char&gt; &lt;char&gt; &lt;char&gt;    &lt;int&gt;    &lt;int&gt; &lt;int&gt;    &lt;num&gt;
## 1:  2014     1     1        14        13      AA    JFK    LAX      359     2475     9 413.6490
## 2:  2014     1     1        -3        13      AA    JFK    LAX      363     2475    11 409.0909
## 3:  2014     1     1         2         9      AA    JFK    LAX      351     2475    19 423.0769
## 4:  2014     1     1        -8       -26      AA    LGA    PBI      157     1035     7 395.5414
## 5:  2014     1     1         2         1      AA    JFK    LAX      350     2475    13 424.2857
## 6:  2014     1     1         4         0      AA    EWR    LAX      339     2454    18 434.3363
</code></pre>
<pre><code class="language-r">head(ans)
</code></pre>
<pre><code>##    month max_speed
##    &lt;int&gt;     &lt;num&gt;
## 1:     1  535.6425
## 2:     2  535.6425
## 3:     3  549.0756
## 4:     4  585.6000
## 5:     5  544.2857
## 6:     6  608.5714
</code></pre>
<ul>
<li>
<p>Tenga en cuenta que se ha añadido la nueva columna <code>speed</code> a la tabla de datos <code>flights</code>. Esto se debe a que <code>:=</code> realiza operaciones por referencia. Dado que <code>DT</code> (el argumento de la función) y <code>flights</code> hacen referencia al mismo objeto en memoria, modificar <code>DT</code> también afecta a <code>flights</code>.</p>
</li>
<li>
<p>Y <code>ans</code> contiene la velocidad máxima para cada mes.</p>
</li>
</ul>
<h3 id="sec:b-la-funci-n-copy">b) La función <code>copy()</code></h3>
<p>En la sección anterior, usamos <code>:=</code> por su efecto secundario. Sin embargo, esto no siempre es deseable. A veces, queremos pasar un objeto <em>data.table</em> a una función y usar el operador <code>:=</code>, pero no queremos actualizar el objeto original. Podemos lograrlo usando la función <code>copy()</code>.</p>
<p>La función <code>copy()</code> copia <em>en profundidad</em> el objeto de entrada y, por lo tanto, cualquier operación de actualización por referencia posterior realizada en el objeto copiado no afectará al objeto original.</p>
<h1></h1>
<p>Hay dos lugares particulares donde la función <code>copy()</code> es esencial:</p>
<ol>
<li>
<p>A diferencia de lo visto en el punto anterior, es posible que no queramos que la tabla de datos de entrada de una función se modifique <em>por referencia</em>. Por ejemplo, consideremos la tarea de la sección anterior, excepto que no queremos modificar <code>flights</code> por referencia.</p>
<p>Let’s first delete the <code>speed</code> column we generated in the previous section.</p>
<pre><code class="language-r">flights[, speed := NULL]
</code></pre>
<p>Now, we could accomplish the task as follows:</p>
<pre><code class="language-r">foo &lt;- function(DT) {
  DT &lt;- copy(DT)                              ## deep copy
  DT[, speed := distance / (air_time/60)]     ## doesn't affect 'flights'
  DT[, .(max_speed = max(speed)), by = month]
}
ans &lt;- foo(flights)
head(flights)
</code></pre>
<pre><code>##     year month   day dep_delay arr_delay carrier origin   dest air_time distance  hour
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;     &lt;int&gt;     &lt;int&gt;  &lt;char&gt; &lt;char&gt; &lt;char&gt;    &lt;int&gt;    &lt;int&gt; &lt;int&gt;
## 1:  2014     1     1        14        13      AA    JFK    LAX      359     2475     9
## 2:  2014     1     1        -3        13      AA    JFK    LAX      363     2475    11
## 3:  2014     1     1         2         9      AA    JFK    LAX      351     2475    19
## 4:  2014     1     1        -8       -26      AA    LGA    PBI      157     1035     7
## 5:  2014     1     1         2         1      AA    JFK    LAX      350     2475    13
## 6:  2014     1     1         4         0      AA    EWR    LAX      339     2454    18
</code></pre>
<pre><code class="language-r">head(ans)
</code></pre>
<pre><code>##    month max_speed
##    &lt;int&gt;     &lt;num&gt;
## 1:     1  535.6425
## 2:     2  535.6425
## 3:     3  549.0756
## 4:     4  585.6000
## 5:     5  544.2857
## 6:     6  608.5714
</code></pre>
</li>
</ol>
<ul>
<li>
<p>El uso de la función <code>copy()</code> no actualizó la tabla de datos <code>flights</code> por referencia. No contiene la columna <code>speed</code>.</p>
</li>
<li>
<p>Y <code>ans</code> contiene la velocidad máxima correspondiente a cada mes.</p>
</li>
</ul>
<p>Sin embargo, podríamos mejorar esta funcionalidad aún más mediante una copia superficial en lugar de una copia profunda. De hecho, nos gustaría mucho <a href="https://github.com/Rdatatable/data.table/issues/617">ofrecer esta funcionalidad para la versión <code>v1.9.8</code></a>. Volveremos a abordar este tema en la viñeta sobre el diseño de data.table.</p>
<h1></h1>
<ol start="2">
<li>
<p>Cuando almacenamos los nombres de las columnas en una variable, por ejemplo, <code>DT_n = names(DT)</code>, y luego <em>añadimos/actualizamos/eliminamos</em> columnas <em>por referencia</em>, también modificaríamos <code>DT_n</code>, a menos que hagamos <code>copy(names(DT))</code>.</p>
<pre><code class="language-r">DT = data.table(x = 1L, y = 2L)
DT_n = names(DT)
DT_n
</code></pre>
<pre><code>## [1] &quot;x&quot; &quot;y&quot;
</code></pre>
<pre><code class="language-r">## add a new column by reference
DT[, z := 3L]

## DT_n also gets updated
DT_n
</code></pre>
<pre><code>## [1] &quot;x&quot; &quot;y&quot; &quot;z&quot;
</code></pre>
<pre><code class="language-r">## use `copy()`
DT_n = copy(names(DT))
DT[, w := 4L]

## DT_n doesn't get updated
DT_n
</code></pre>
<pre><code>## [1] &quot;x&quot; &quot;y&quot; &quot;z&quot;
</code></pre>
</li>
</ol>
<h3 id="sec:c-selecci-n-de-columnas-vs-col">c) Selección de columnas: <code>$</code> / <code>[[...]]</code> vs <code>[, col]</code></h3>
<p>Cuando se extrae una sola columna como vector, existe una diferencia sutil pero importante entre los métodos R estándar ($ y [[…]]) y la expresión j de data.table. DT$col y DT[[‘col’]] pueden devolver una referencia a la columna, mientras que DT[, col] siempre devuelve una copia.</p>
<p>Un breve ejemplo:</p>
<pre><code class="language-r">DT = data.table(a = 1:3)

# three ways to get the column
x_ref = DT$a        # may be a reference
y_cpy = DT[, a]     # always a copy
z_cpy = copy(DT$a)  # forced copy

# modify DT by reference
DT[, a := a + 10L]

# observe results
x_ref   # may show 11 12 13
</code></pre>
<pre><code>## [1] 1 2 3
</code></pre>
<pre><code class="language-r">y_cpy   # 1 2 3
</code></pre>
<pre><code>## [1] 1 2 3
</code></pre>
<pre><code class="language-r">z_cpy   # 1 2 3
</code></pre>
<pre><code>## [1] 1 2 3
</code></pre>
<p>Para seleccionar una sola columna como vector, recuerde: =====- <code>DT[, mycol]</code> es más seguro, ya que siempre devuelve una copia nueva e independiente.</p>
<ul>
<li><code>DT$mycol</code> es rápido, pero puede devolver una referencia. Use <code>copy(DT$mycol)</code> para garantizar la independencia.=====</li>
</ul>
<h2 id="sec:resumen">Resumen</h2>
<h4 id="sec:el-operador">El operador <code>:=</code></h4>
<ul>
<li>
<p>Se utiliza para <em>agregar/actualizar/eliminar</em> columnas por referencia.</p>
</li>
<li>
<p>También vimos cómo usar <code>:=</code> junto con <code>i</code> y <code>by</code> de la misma manera que en la viñeta <a href="datatable-intro.html"><code>vignette(&quot;datatable-intro&quot;, package=&quot;data.table&quot;)</code></a>. Podemos usar <code>keyby</code>, encadenar operaciones y pasar expresiones a <code>by</code> de la misma manera. La sintaxis es <em>consistente</em>.</p>
</li>
<li>
<p>Podemos usar <code>:=</code> por su efecto secundario o usar <code>copy()</code> para no modificar el objeto original mientras actualizamos por referencia.</p>
</li>
</ul>
<h1></h1>
<p>Hasta ahora hemos visto mucho sobre <code>j</code> y cómo combinarlo con <code>by</code> y poco de <code>i</code>. Volvamos a centrarnos en <code>i</code> en la <a href="datatable-keys-fast-subset.html">siguiente viñeta (<code>vignette(&quot;datatable-keys-fast-subset&quot;, package=&quot;data.table&quot;)</code>)</a> para realizar subconjuntos ultrarrápidos mediante la <em>codificación de data.tables</em>.</p>
<hr />
</div>
<script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-core.min.js" defer></script>
<script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/plugins/autoloader/prism-autoloader.min.js" defer></script>
</body>
</html>
